server:
  port: 8080


spring:
  datasource:
    username: root
    password: qwer1234
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
    #  show-sql: true
    open-in-view: true

  logging:
    level:
      org.hibernate.SQL: info

indexing-settings:
  sites:
    - url: https://nikoartgallery.com/news/all
      name: Niko art gallery
    - url: https://www.svetlovka.ru/
      name: Библиотека им.Светлова
    - url: http://radiomv.ru/actions/
      name: RadioMV
    - url: https://at-store.ru/
      name: at-store
    - url: https://et-cetera.ru/mobile/
      name: et-cetera.ru
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://dombulgakova.ru/
      name: dombulgakova